name: fg_count
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - binutils_impl_linux-64=2.40
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - comm=0.2.2
  - conda-gcc-specs=15.1.0
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - gcc=15.1.0
  - gcc_impl_linux-64=15.1.0
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kernel-headers_linux-64=2.6.32
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-devel_linux-64=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libsanitizer=15.1.0
  - libsodium=1.0.18
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.5.0
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - torchaudio=2.3.0
  - torchvision=0.18.0
  - readline=8.2
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sysroot_linux-64=2.12
  - tk=8.6.14
  - traitlets=5.14.3
  - typing_extensions=4.14.0
  - wcwidth=0.2.13
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - pip:
    - accelerate==1.6.0
    - addict==2.4.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.11
    - aiosignal==1.3.2
    - alembic==1.16.1
    - annotated-types==0.7.0
    - async-timeout==5.0.1
    - attrs==25.3.0
    - banal==1.0.6
    - cachetools==5.5.2
    - certifi==2025.4.26
    - charset-normalizer==3.4.2
    - click==8.2.1
    - contourpy==1.3.2
    - cycler==0.12.1
    - cython==3.1.2
    - datasets==3.6.0
    - debugpy==1.8.14
    - deepspeed==0.17.0
    - defusedxml==0.7.1
    - dill==0.3.8
    - einops==0.8.1
    - filelock==3.13.1
    - fonttools==4.58.2
    - frozenlist==1.6.2
    - fsspec==2024.6.1
    - gitdb==4.0.12
    - gitpython==3.1.44
    - google-api-core==2.25.1
    - google-api-python-client==2.179.0
    - google-auth==2.40.3
    - google-auth-httplib2==0.2.0
    - google-auth-oauthlib==1.2.2
    - googleapis-common-protos==1.70.0
    - greenlet==3.2.3
    - hf-xet==1.1.3
    - hjson==3.1.0
    - httplib2==0.22.0
    - huggingface-hub==0.32.4
    - idna==3.10
    - imageio==2.37.0
    - jinja2==3.1.4
    - kiwisolver==1.4.8
    - mako==1.3.10
    - markupsafe==2.1.5
    - matplotlib==3.10.3
    - mpmath==1.3.0
    - msgpack==1.1.0
    - multidict==6.4.4
    - multiprocess==0.70.16
    - networkx==3.3
    - ninja==1.11.1.4
    - numpy==1.26.4
    - oauthlib==3.3.1
    - opencv-python==4.9.0.80
    - pandas==2.3.0
    - pillow==11.0.0
    - propcache==0.3.1
    - proto-plus==1.26.1
    - protobuf==6.31.1
    - psutil==7.0.0
    - py-cpuinfo==9.0.0
    - pyarrow==20.0.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pycocotools==2.0.10
    - pydantic==2.11.5
    - pydantic-core==2.33.2
    - pynvml==12.0.0
    - pyparsing==3.2.3
    - pytz==2025.2
    - pyyaml==6.0.2
    - pyzmq==24.0.1
    - regex==2024.11.6
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - rsa==4.9.1
    - safetensors==0.5.3
    - scipy==1.15.3
    - seaborn==0.13.2
    - sentry-sdk==2.29.1
    - setproctitle==1.3.6
    - setuptools==78.1.1
    - smmap==5.0.2
    - sqlalchemy==1.4.54
    - supervision==0.25.1
    - sympy==1.13.1
    - timm==1.0.17
    - tokenizers==0.19.1
    - tomli==2.2.1
    - triton==2.3.0
    - typing-extensions==4.12.2
    - typing-inspection==0.4.1
    - tzdata==2025.2
    - uritemplate==4.2.0
    - urllib3==2.4.0
    - wandb==0.20.1
    - wheel==0.45.1
    - xxhash==3.5.0
    - yapf==0.43.0
    - yarl==1.20.0